// Shared Resala SMS provider helper.
// If RESALA_API_KEY is not configured, returns provider_not_configured
// without throwing — callers must surface a clear message to the user.

export interface SendResult {
  ok: boolean;
  status: "sent" | "failed" | "provider_not_configured" | "queued";
  providerResponse: string;
}

export interface SendOtpResult extends SendResult {
  pin?: string; // OTP generated by Resala (only present on success)
}

/**
 * Sends an OTP via Resala's /api/v1/pins endpoint. Resala generates the pin
 * and returns it in the response — we surface it back to the caller so the
 * hash can be persisted server-side.
 */
export async function sendOtpViaResala(opts: {
  phone: string;           // international, no '+': e.g. 218910024433
  serviceName?: string;
  length?: 4 | 5 | 6;
  lang?: "ar" | "en";
}): Promise<SendOtpResult> {
  const apiKey = Deno.env.get("RESALA_API_KEY");
  if (!apiKey) {
    return { ok: false, status: "provider_not_configured", providerResponse: "RESALA_API_KEY not set" };
  }
  const serviceName = opts.serviceName || Deno.env.get("RESALA_SENDER") || "DarAlzuyout";
  const len = opts.length ?? 6;
  const lang = opts.lang ?? "ar";
  const url = `https://dev.resala.ly/api/v1/pins?service_name=${encodeURIComponent(serviceName)}&len=${len}&lang=${lang}`;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({ phone: opts.phone, region: "LY" }),
    });
    const text = await res.text();
    if (!res.ok) {
      return { ok: false, status: "failed", providerResponse: `HTTP ${res.status}: ${text.slice(0, 500)}` };
    }
    let pin: string | undefined;
    try { pin = JSON.parse(text)?.pin; } catch { /* ignore */ }
    if (!pin) {
      return { ok: false, status: "failed", providerResponse: `no_pin_in_response: ${text.slice(0, 300)}` };
    }
    return { ok: true, status: "sent", providerResponse: text.slice(0, 300), pin };
  } catch (e) {
    return { ok: false, status: "failed", providerResponse: String(e).slice(0, 500) };
  }
}

export async function sendSmsViaResala(opts: {
  to: string;
  body: string;
  sender?: string;
}): Promise<SendResult> {
  const apiKey = Deno.env.get("RESALA_API_KEY");
  if (!apiKey) {
    return {
      ok: false,
      status: "provider_not_configured",
      providerResponse: "RESALA_API_KEY not set",
    };
  }
  const sender = opts.sender || Deno.env.get("RESALA_SENDER") || "DarAlzuyout";

  try {
    // Resala.ly REST API (per http://dev.resala.ly/)
    // Endpoint and body shape kept generic; adapter can be tightened
    // once a real account/credentials confirm exact contract.
    const res = await fetch("https://api.resala.ly/api/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        to: opts.to,
        body: opts.body,
        sender,
      }),
    });
    const text = await res.text();
    if (!res.ok) {
      return { ok: false, status: "failed", providerResponse: `HTTP ${res.status}: ${text.slice(0, 500)}` };
    }
    return { ok: true, status: "sent", providerResponse: text.slice(0, 500) };
  } catch (e) {
    return { ok: false, status: "failed", providerResponse: String(e).slice(0, 500) };
  }
}

export function normalizePhone(input: string): string {
  return (input || "").replace(/\D/g, "");
}

export function isValidLibyanPhone(phone: string): boolean {
  const d = normalizePhone(phone);
  return /^09\d{8}$/.test(d) || /^2189\d{8}$/.test(d);
}

export function toE164Libya(phone: string): string {
  const d = normalizePhone(phone);
  if (d.startsWith("218")) return "+" + d;
  if (d.startsWith("09")) return "+218" + d.slice(1);
  return "+" + d;
}

export async function sha256Hex(input: string): Promise<string> {
  const buf = new TextEncoder().encode(input);
  const hash = await crypto.subtle.digest("SHA-256", buf);
  return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

export const CORS_ALLOWED_ORIGIN_PATTERNS: RegExp[] = [
  /^https?:\/\/localhost(:\d+)?$/i,
  /^https?:\/\/127\.0\.0\.1(:\d+)?$/i,
  // Add production domain(s) here, e.g.:
  // /^https?:\/\/(.*\.)?daralzuyout\.ly$/i,
];

export function corsHeadersFor(origin: string | null): Record<string, string> {
  const allowed = origin && CORS_ALLOWED_ORIGIN_PATTERNS.some((re) => re.test(origin));
  return {
    "Access-Control-Allow-Origin": allowed ? origin! : "null",
    "Vary": "Origin",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
  };
}