/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as Portal9f3kSecureRouteImport } from './routes/portal-9f3k-secure'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServiceRecordsRouteImport } from './routes/admin.service-records'
import { Route as AdminScanCardRouteImport } from './routes/admin.scan-card'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminQuickServiceRouteImport } from './routes/admin.quick-service'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const Portal9f3kSecureRoute = Portal9f3kSecureRouteImport.update({
  id: '/portal-9f3k-secure',
  path: '/portal-9f3k-secure',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceRecordsRoute = AdminServiceRecordsRouteImport.update({
  id: '/service-records',
  path: '/service-records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanCardRoute = AdminScanCardRouteImport.update({
  id: '/scan-card',
  path: '/scan-card',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickServiceRoute = AdminQuickServiceRouteImport.update({
  id: '/quick-service',
  path: '/quick-service',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/portal-9f3k-secure': typeof Portal9f3kSecureRoute
  '/services': typeof ServicesRoute
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quick-service': typeof AdminQuickServiceRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/scan-card': typeof AdminScanCardRoute
  '/admin/service-records': typeof AdminServiceRecordsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/portal-9f3k-secure': typeof Portal9f3kSecureRoute
  '/services': typeof ServicesRoute
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quick-service': typeof AdminQuickServiceRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/scan-card': typeof AdminScanCardRoute
  '/admin/service-records': typeof AdminServiceRecordsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/portal-9f3k-secure': typeof Portal9f3kSecureRoute
  '/services': typeof ServicesRoute
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quick-service': typeof AdminQuickServiceRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/scan-card': typeof AdminScanCardRoute
  '/admin/service-records': typeof AdminServiceRecordsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/join'
    | '/portal-9f3k-secure'
    | '/services'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/broadcasts'
    | '/admin/promotions'
    | '/admin/quick-service'
    | '/admin/reminders'
    | '/admin/reviews'
    | '/admin/scan-card'
    | '/admin/service-records'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/faq'
    | '/join'
    | '/portal-9f3k-secure'
    | '/services'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/broadcasts'
    | '/admin/promotions'
    | '/admin/quick-service'
    | '/admin/reminders'
    | '/admin/reviews'
    | '/admin/scan-card'
    | '/admin/service-records'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/admin/customers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/join'
    | '/portal-9f3k-secure'
    | '/services'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/broadcasts'
    | '/admin/promotions'
    | '/admin/quick-service'
    | '/admin/reminders'
    | '/admin/reviews'
    | '/admin/scan-card'
    | '/admin/service-records'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JoinRoute: typeof JoinRoute
  Portal9f3kSecureRoute: typeof Portal9f3kSecureRoute
  ServicesRoute: typeof ServicesRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-9f3k-secure': {
      id: '/portal-9f3k-secure'
      path: '/portal-9f3k-secure'
      fullPath: '/portal-9f3k-secure'
      preLoaderRoute: typeof Portal9f3kSecureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-records': {
      id: '/admin/service-records'
      path: '/service-records'
      fullPath: '/admin/service-records'
      preLoaderRoute: typeof AdminServiceRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan-card': {
      id: '/admin/scan-card'
      path: '/scan-card'
      fullPath: '/admin/scan-card'
      preLoaderRoute: typeof AdminScanCardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-service': {
      id: '/admin/quick-service'
      path: '/quick-service'
      fullPath: '/admin/quick-service'
      preLoaderRoute: typeof AdminQuickServiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminQuickServiceRoute: typeof AdminQuickServiceRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminScanCardRoute: typeof AdminScanCardRoute
  AdminServiceRecordsRoute: typeof AdminServiceRecordsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminQuickServiceRoute: AdminQuickServiceRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminScanCardRoute: AdminScanCardRoute,
  AdminServiceRecordsRoute: AdminServiceRecordsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JoinRoute: JoinRoute,
  Portal9f3kSecureRoute: Portal9f3kSecureRoute,
  ServicesRoute: ServicesRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
